name: Run terraform apply

on:
  workflow_dispatch:

#  push:
#    branches:
#      - 'main'
#    paths:
#      - '**.tf'

jobs:

  setup-and-apply:
    name: Setup and Apply
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: plan
      run: terraform apply -auto-approve -no-color